# Optimus
Uses python3.8

In [42]:
from optimus import Optimus

op = Optimus("pandas")

df = op.create.dataframe({
    'A': ['a', 'b', 'c', 'd'],
    'B': [1, 3, 5, 7],
    'C': [2, 4, 6, None],
    'D': ['1980/04/10', '1980/04/10', '1980/04/10', '1980/04/10'],
    'E': [1998, 1998, 2004, 2001],
})
display(df)

ModuleNotFoundError: No module named 'databricks'

In [35]:
df.cols.quality()

/home/adriana/Documents/ML-Data-Prep-Zoo/venv_optimus/lib/python3.8/site-packages/numpy/lib/function_base.py:2412: RuntimeWarning: invalid value encountered in isintlike (vectorized)
  outputs = ufunc(*inputs)

{'A': {'match': 4,
  'missing': 0,
  'mismatch': 0,
  'inferred_data_type': 'string'},
 'B': {'match': 4, 'missing': 0, 'mismatch': 0, 'inferred_data_type': 'int'},
 'C': {'match': 3, 'missing': 1, 'mismatch': 0, 'inferred_data_type': 'int'},
 'D': {'match': 4,
  'missing': 0,
  'mismatch': 0,
  'inferred_data_type': 'string'},
 'E': {'match': 4, 'missing': 0, 'mismatch': 0, 'inferred_data_type': 'int'}}

In [36]:
df.profile()

{'columns': {'A': {'stats': {'match': 4,
    'missing': 0,
    'mismatch': 0,
    'inferred_data_type': {'data_type': 'string', 'categorical': True},
    'frequency': [{'value': 'a', 'count': 1},
     {'value': 'b', 'count': 1},
     {'value': 'c', 'count': 1},
     {'value': 'd', 'count': 1}],
    'count_uniques': 4},
   'data_type': 'object'},
  'B': {'stats': {'match': 4,
    'missing': 0,
    'mismatch': 0,
    'inferred_data_type': {'data_type': 'int', 'categorical': True},
    'frequency': [{'value': 1, 'count': 1},
     {'value': 3, 'count': 1},
     {'value': 5, 'count': 1},
     {'value': 7, 'count': 1}],
    'count_uniques': 4},
   'data_type': 'int64'},
  'C': {'stats': {'match': 3,
    'missing': 1,
    'mismatch': 0,
    'inferred_data_type': {'data_type': 'int', 'categorical': True},
    'frequency': [{'value': 2.0, 'count': 1},
     {'value': 4.0, 'count': 1},
     {'value': 6.0, 'count': 1},
     {'value': nan, 'count': 1}],
    'count_uniques': 4},
   'data_type': 'float64'},
  'D': {'stats': {'match': 4,
    'missing': 0,
    'mismatch': 0,
    'inferred_data_type': {'data_type': 'string', 'categorical': True},
    'frequency': [{'value': '1980/04/10', 'count': 4}],
    'count_uniques': 1},
   'data_type': 'object'},
  'E': {'stats': {'match': 4,
    'missing': 0,
    'mismatch': 0,
    'inferred_data_type': {'data_type': 'int', 'categorical': True},
    'frequency': [{'value': 1998, 'count': 2},
     {'value': 2001, 'count': 1},
     {'value': 2004, 'count': 1}],
    'count_uniques': 3},
   'data_type': 'int64'}},
 'name': None,
 'file_name': None,
 'summary': {'rows_count': 4,
  'missing_count': 0,
  'cols_count': 5,
  'data_types_list': ['object', 'int64', 'float64'],
  'total_count_data_types': 3,
  'p_missing': 0.0}}

In [12]:
df.cols.infer_types("A")

In [20]:
# df.cols.count_by_dtypes("*")

df.cols.__dict__

t_methods = [method_name for method_name in dir(df.cols)
                  if callable(getattr(df.cols, method_name))]
print(t_methods)

['__class__', '__delattr__', '__dir__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_any_mask', '_calculate_pattern_counts', '_count_mask', '_data_type', '_date_format', '_map', '_mask', '_math', '_names', '_replace', '_replace_regex', '_round', '_select', '_series_to_dict', '_series_to_pandas', '_set', '_set_transformed_stat', '_transformed', '_unnest', 'abs', 'acos', 'acosh', 'add', 'agg_exprs', 'any_array', 'any_between', 'any_boolean', 'any_containing', 'any_credit_card_number', 'any_datetime', 'any_duplicated', 'any_email', 'any_empty', 'any_ending_with', 'any_equal', 'any_expression', 'any_float', 'any_gender', 'any_greater_than', 'any_greater_than_equal', 'any_http_code', 'any_int', 'any_ip', 'any_less_than', 'any_less_than_equal', 'any_match', 'any_match_data_type', 'any_match_pattern', 'any_match_regex', 'any_mismatch', 'any_missing', 'any_nan', 'any_none', 'any_not_equal', 'any_null', 'any_numeric', 'any_object', 'any_phone_number', 'any_social_security_number', 'any_starting_with', 'any_str', 'any_url', 'any_value_in', 'any_zip_code', 'append', 'apply', 'apply_by_data_types', 'array_values', 'asin', 'asinh', 'assign', 'astype', 'atan', 'atanh', 'bag_of_words', 'between', 'boolean_values', 'boxplot', 'capitalize', 'cast', 'ceil', 'clip', 'concat', 'contains', 'copy', 'correlation', 'cos', 'cosh', 'count', 'count_array', 'count_between', 'count_boolean', 'count_containing', 'count_credit_card_number', 'count_data_type', 'count_datetime', 'count_duplicated', 'count_email', 'count_empty', 'count_ending_with', 'count_equal', 'count_expression', 'count_float', 'count_gender', 'count_greater_than', 'count_greater_than_equal', 'count_http_code', 'count_int', 'count_ip', 'count_less_than', 'count_less_than_equal', 'count_match', 'count_match_pattern', 'count_mismatch', 'count_missings', 'count_nan', 'count_none', 'count_not_equal', 'count_nulls', 'count_numeric', 'count_object', 'count_phone_number', 'count_regex', 'count_social_security_number', 'count_starting_with', 'count_str', 'count_uniques', 'count_url', 'count_values_in', 'count_zeros', 'count_zip_code', 'credit_card_number_values', 'cross_tab', 'cummax', 'cummin', 'cumprod', 'cumsum', 'cut', 'data_type', 'date_format', 'date_formats', 'datetime_values', 'day', 'days_between', 'div', 'domain', 'double_metaphone', 'drop', 'duplicate', 'duplicated', 'email_domain', 'email_username', 'email_values', 'empty', 'ends_with', 'equal', 'exec_agg', 'exp', 'expand_contracted_words', 'expression', 'extract', 'fill_na', 'find', 'fingerprint', 'float_values', 'floor', 'format_agg', 'format_date', 'frequency', 'gender_values', 'get', 'greater_than', 'greater_than_equal', 'groupby', 'heatmap', 'hist', 'host', 'hour', 'hours_between', 'http_code_values', 'impute', 'index_to_string', 'infer_data_types', 'infer_date_formats', 'infer_type', 'inferred_data_type', 'int_values', 'ip_values', 'iqr', 'item', 'join', 'keep', 'kurtosis', 'left', 'lemmatize_verbs', 'len', 'less_than', 'less_than_equal', 'levenshtein', 'ln', 'log', 'lower', 'mad', 'match', 'match_data_type', 'match_pattern', 'match_rating_codex', 'match_regex', 'max', 'max_abs_scaler', 'mean', 'median', 'metaphone', 'mid', 'min', 'min_max_scaler', 'minute', 'minutes_between', 'mismatch', 'missing', 'mod', 'mode', 'modified_z_score', 'month', 'months_between', 'move', 'mul', 'names', 'nan', 'nest', 'ngram_fingerprint', 'ngrams', 'none', 'normalize_chars', 'normalize_spaces', 'not_equal', 'null', 'num_to_words', 'numeric_values', 'nysiis', 'object_values', 'one_hot_encode', 'pad', 'parse_inferred_types', 'pattern', 'pattern_counts', 'percentile', 'phone_number_values', 'port', 'pos', 'pow', 'prod', 'profile', 'qcut', 'quality', 'range', 'rdiv', 'reciprocal', 'remove', 'remove_numbers', 'remove_special_chars', 'remove_stopwords', 'remove_urls', 'remove_white_spaces', 'rename', 'replace', 'replace_regex', 'reverse', 'right', 'round', 'schema_data_type', 'second', 'seconds_between', 'select', 'set', 'set_data_type', 'set_date_format', 'sin', 'sinh', 'skew', 'slice', 'social_security_number_values', 'sort', 'soundex', 'sqrt', 'standard_scaler', 'starts_with', 'std', 'stem_verbs', 'stem_words', 'str_values', 'string_to_index', 'strip', 'strip_html', 'sub', 'sub_domain', 'substring', 'sum', 'tan', 'tanh', 'tf_idf', 'time_between', 'title', 'to_boolean', 'to_datetime', 'to_float', 'to_integer', 'to_list', 'to_numeric', 'to_string', 'to_timestamp', 'top_domain', 'trim', 'unique', 'unique_values', 'unnest', 'unset_data_type', 'unset_date_format', 'upper', 'url_file', 'url_fragment', 'url_path', 'url_query', 'url_scheme', 'url_values', 'value_in', 'var', 'weekday', 'word_count', 'word_tokenize', 'year', 'years_between', 'z_score', 'zip_code_values']

In [21]:
[method_name for method_name in dir(df.cols)
                  if callable(getattr(df.cols, method_name))]

['__class__',
 '__delattr__',
 '__dir__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_any_mask',
 '_calculate_pattern_counts',
 '_count_mask',
 '_data_type',
 '_date_format',
 '_map',
 '_mask',
 '_math',
 '_names',
 '_replace',
 '_replace_regex',
 '_round',
 '_select',
 '_series_to_dict',
 '_series_to_pandas',
 '_set',
 '_set_transformed_stat',
 '_transformed',
 '_unnest',
 'abs',
 'acos',
 'acosh',
 'add',
 'agg_exprs',
 'any_array',
 'any_between',
 'any_boolean',
 'any_containing',
 'any_credit_card_number',
 'any_datetime',
 'any_duplicated',
 'any_email',
 'any_empty',
 'any_ending_with',
 'any_equal',
 'any_expression',
 'any_float',
 'any_gender',
 'any_greater_than',
 'any_greater_than_equal',
 'any_http_code',
 'any_int',
 'any_ip',
 'any_less_than',
 'any_less_than_equal',
 'any_match',
 'any_match_data_type',
 'any_match_pattern',
 'any_match_regex',
 'any_mismatch',
 'any_missing',
 'any_nan',
 'any_none',
 'any_not_equal',
 'any_null',
 'any_numeric',
 'any_object',
 'any_phone_number',
 'any_social_security_number',
 'any_starting_with',
 'any_str',
 'any_url',
 'any_value_in',
 'any_zip_code',
 'append',
 'apply',
 'apply_by_data_types',
 'array_values',
 'asin',
 'asinh',
 'assign',
 'astype',
 'atan',
 'atanh',
 'bag_of_words',
 'between',
 'boolean_values',
 'boxplot',
 'capitalize',
 'cast',
 'ceil',
 'clip',
 'concat',
 'contains',
 'copy',
 'correlation',
 'cos',
 'cosh',
 'count',
 'count_array',
 'count_between',
 'count_boolean',
 'count_containing',
 'count_credit_card_number',
 'count_data_type',
 'count_datetime',
 'count_duplicated',
 'count_email',
 'count_empty',
 'count_ending_with',
 'count_equal',
 'count_expression',
 'count_float',
 'count_gender',
 'count_greater_than',
 'count_greater_than_equal',
 'count_http_code',
 'count_int',
 'count_ip',
 'count_less_than',
 'count_less_than_equal',
 'count_match',
 'count_match_pattern',
 'count_mismatch',
 'count_missings',
 'count_nan',
 'count_none',
 'count_not_equal',
 'count_nulls',
 'count_numeric',
 'count_object',
 'count_phone_number',
 'count_regex',
 'count_social_security_number',
 'count_starting_with',
 'count_str',
 'count_uniques',
 'count_url',
 'count_values_in',
 'count_zeros',
 'count_zip_code',
 'credit_card_number_values',
 'cross_tab',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'cut',
 'data_type',
 'date_format',
 'date_formats',
 'datetime_values',
 'day',
 'days_between',
 'div',
 'domain',
 'double_metaphone',
 'drop',
 'duplicate',
 'duplicated',
 'email_domain',
 'email_username',
 'email_values',
 'empty',
 'ends_with',
 'equal',
 'exec_agg',
 'exp',
 'expand_contracted_words',
 'expression',
 'extract',
 'fill_na',
 'find',
 'fingerprint',
 'float_values',
 'floor',
 'format_agg',
 'format_date',
 'frequency',
 'gender_values',
 'get',
 'greater_than',
 'greater_than_equal',
 'groupby',
 'heatmap',
 'hist',
 'host',
 'hour',
 'hours_between',
 'http_code_values',
 'impute',
 'index_to_string',
 'infer_data_types',
 'infer_date_formats',
 'infer_type',
 'inferred_data_type',
 'int_values',
 'ip_values',
 'iqr',
 'item',
 'join',
 'keep',
 'kurtosis',
 'left',
 'lemmatize_verbs',
 'len',
 'less_than',
 'less_than_equal',
 'levenshtein',
 'ln',
 'log',
 'lower',
 'mad',
 'match',
 'match_data_type',
 'match_pattern',
 'match_rating_codex',
 'match_regex',
 'max',
 'max_abs_scaler',
 'mean',
 'median',
 'metaphone',
 'mid',
 'min',
 'min_max_scaler',
 'minute',
 'minutes_between',
 'mismatch',
 'missing',
 'mod',
 'mode',
 'modified_z_score',
 'month',
 'months_between',
 'move',
 'mul',
 'names',
 'nan',
 'nest',
 'ngram_fingerprint',
 'ngrams',
 'none',
 'normalize_chars',
 'normalize_spaces',
 'not_equal',
 'null',
 'num_to_words',
 'numeric_values',
 'nysiis',
 'object_values',
 'one_hot_encode',
 'pad',
 'parse_inferred_types',
 'pattern',
 'pattern_counts',
 'percentile',
 'phone_number_values',
 'port',
 'pos',
 'pow',
 'prod',
 'profile',
 'qcut',
 'quality',
 'range',
 'rdiv',
 'reciprocal',
 'remove',
 'remove_numbers',
 'remove_special_chars',
 'remove_stopwords',
 'remove_urls',
 'remove_white_spaces',
 'rename',
 'replace',
 'replace_regex',
 'reverse',
 'right',
 'round',
 'schema_data_type',
 'second',
 'seconds_between',
 'select',
 'set',
 'set_data_type',
 'set_date_format',
 'sin',
 'sinh',
 'skew',
 'slice',
 'social_security_number_values',
 'sort',
 'soundex',
 'sqrt',
 'standard_scaler',
 'starts_with',
 'std',
 'stem_verbs',
 'stem_words',
 'str_values',
 'string_to_index',
 'strip',
 'strip_html',
 'sub',
 'sub_domain',
 'substring',
 'sum',
 'tan',
 'tanh',
 'tf_idf',
 'time_between',
 'title',
 'to_boolean',
 'to_datetime',
 'to_float',
 'to_integer',
 'to_list',
 'to_numeric',
 'to_string',
 'to_timestamp',
 'top_domain',
 'trim',
 'unique',
 'unique_values',
 'unnest',
 'unset_data_type',
 'unset_date_format',
 'upper',
 'url_file',
 'url_fragment',
 'url_path',
 'url_query',
 'url_scheme',
 'url_values',
 'value_in',
 'var',
 'weekday',
 'word_count',
 'word_tokenize',
 'year',
 'years_between',
 'z_score',
 'zip_code_values']

In [27]:
df

A                   B            C  D
(object)      (int64)    (float64)  (object)
----------  ---------  -----------  ----------
a                   1            2  1980/04/10
b                   3            4  1980/04/10
c                   5            6  1980/04/10
d                   7          nan  1980/04/10

In [37]:
df.cols.infer_type()

{'A': {'data_type': 'string', 'categorical': True},
 'B': {'data_type': 'int', 'categorical': True},
 'C': {'data_type': 'int', 'categorical': True},
 'D': {'data_type': 'string', 'categorical': True},
 'E': {'data_type': 'int', 'categorical': True}}

In [38]:
df.profile(bins=5)

{'columns': {'A': {'stats': {'match': 4,
    'missing': 0,
    'mismatch': 0,
    'inferred_data_type': {'data_type': 'string', 'categorical': True},
    'frequency': [{'value': 'a', 'count': 1},
     {'value': 'b', 'count': 1},
     {'value': 'c', 'count': 1},
     {'value': 'd', 'count': 1}],
    'count_uniques': 4},
   'data_type': 'object'},
  'B': {'stats': {'match': 4,
    'missing': 0,
    'mismatch': 0,
    'inferred_data_type': {'data_type': 'int', 'categorical': True},
    'frequency': [{'value': 1, 'count': 1},
     {'value': 3, 'count': 1},
     {'value': 5, 'count': 1},
     {'value': 7, 'count': 1}],
    'count_uniques': 4},
   'data_type': 'int64'},
  'C': {'stats': {'match': 3,
    'missing': 1,
    'mismatch': 0,
    'inferred_data_type': {'data_type': 'int', 'categorical': True},
    'frequency': [{'value': 2.0, 'count': 1},
     {'value': 4.0, 'count': 1},
     {'value': 6.0, 'count': 1},
     {'value': nan, 'count': 1}],
    'count_uniques': 4},
   'data_type': 'float64'},
  'D': {'stats': {'match': 4,
    'missing': 0,
    'mismatch': 0,
    'inferred_data_type': {'data_type': 'string', 'categorical': True},
    'frequency': [{'value': '1980/04/10', 'count': 4}],
    'count_uniques': 1},
   'data_type': 'object'},
  'E': {'stats': {'match': 4,
    'missing': 0,
    'mismatch': 0,
    'inferred_data_type': {'data_type': 'int', 'categorical': True},
    'frequency': [{'value': 1998, 'count': 2},
     {'value': 2001, 'count': 1},
     {'value': 2004, 'count': 1}],
    'count_uniques': 3},
   'data_type': 'int64'}},
 'name': None,
 'file_name': None,
 'summary': {'rows_count': 4,
  'missing_count': 0,
  'cols_count': 5,
  'data_types_list': ['object', 'int64', 'float64'],
  'total_count_data_types': 3,
  'p_missing': 0.0}}

In [39]:
df.profile.summary()

{'rows_count': 4,
 'missing_count': 0,
 'cols_count': 5,
 'data_types_list': ['object', 'int64', 'float64'],
 'total_count_data_types': 3,
 'p_missing': 0.0}

In [40]:
df.profile.columns()

[{'stats': {'match': 4,
   'missing': 0,
   'mismatch': 0,
   'inferred_data_type': {'data_type': 'string', 'categorical': True},
   'frequency': [{'value': 'a', 'count': 1},
    {'value': 'b', 'count': 1},
    {'value': 'c', 'count': 1},
    {'value': 'd', 'count': 1}],
   'count_uniques': 4},
  'data_type': 'object'},
 {'stats': {'match': 4,
   'missing': 0,
   'mismatch': 0,
   'inferred_data_type': {'data_type': 'int', 'categorical': True},
   'frequency': [{'value': 1, 'count': 1},
    {'value': 3, 'count': 1},
    {'value': 5, 'count': 1},
    {'value': 7, 'count': 1}],
   'count_uniques': 4},
  'data_type': 'int64'},
 {'stats': {'match': 3,
   'missing': 1,
   'mismatch': 0,
   'inferred_data_type': {'data_type': 'int', 'categorical': True},
   'frequency': [{'value': 2.0, 'count': 1},
    {'value': 4.0, 'count': 1},
    {'value': 6.0, 'count': 1},
    {'value': nan, 'count': 1}],
   'count_uniques': 4},
  'data_type': 'float64'},
 {'stats': {'match': 4,
   'missing': 0,
   'mismatch': 0,
   'inferred_data_type': {'data_type': 'string', 'categorical': True},
   'frequency': [{'value': '1980/04/10', 'count': 4}],
   'count_uniques': 1},
  'data_type': 'object'},
 {'stats': {'match': 4,
   'missing': 0,
   'mismatch': 0,
   'inferred_data_type': {'data_type': 'int', 'categorical': True},
   'frequency': [{'value': 1998, 'count': 2},
    {'value': 2001, 'count': 1},
    {'value': 2004, 'count': 1}],
   'count_uniques': 3},
  'data_type': 'int64'}]

In [1]:
from optimus import Optimus

op = Optimus("dask")

df = op.load.csv("store.csv", dtype="str")

distributed.diskutils - INFO - Found stale lock file and directory '/home/adriana/Documents/ML-Data-Prep-Zoo/NewExperiments/dask-worker-space/worker-ooo4t185', purging

In [2]:
df.cols.infer_type()

sample_count = 219

ValueError: sample does not support the number of sampled items parameter, 'n'. Please use the 'frac' parameter instead.

In [49]:
[method_name for method_name in dir(df.cols)
                  if callable(getattr(df.cols, method_name))]

['__class__',
 '__delattr__',
 '__dir__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_any_mask',
 '_calculate_pattern_counts',
 '_count_mask',
 '_data_type',
 '_date_format',
 '_map',
 '_mask',
 '_math',
 '_names',
 '_replace',
 '_replace_regex',
 '_round',
 '_select',
 '_series_to_dict',
 '_series_to_pandas',
 '_set',
 '_set_transformed_stat',
 '_transformed',
 '_unnest',
 'abs',
 'acos',
 'acosh',
 'add',
 'agg_exprs',
 'any_array',
 'any_between',
 'any_boolean',
 'any_containing',
 'any_credit_card_number',
 'any_datetime',
 'any_duplicated',
 'any_email',
 'any_empty',
 'any_ending_with',
 'any_equal',
 'any_expression',
 'any_float',
 'any_gender',
 'any_greater_than',
 'any_greater_than_equal',
 'any_http_code',
 'any_int',
 'any_ip',
 'any_less_than',
 'any_less_than_equal',
 'any_match',
 'any_match_data_type',
 'any_match_pattern',
 'any_match_regex',
 'any_mismatch',
 'any_missing',
 'any_nan',
 'any_none',
 'any_not_equal',
 'any_null',
 'any_numeric',
 'any_object',
 'any_phone_number',
 'any_social_security_number',
 'any_starting_with',
 'any_str',
 'any_url',
 'any_value_in',
 'any_zip_code',
 'append',
 'apply',
 'apply_by_data_types',
 'array_values',
 'asin',
 'asinh',
 'assign',
 'astype',
 'atan',
 'atanh',
 'bag_of_words',
 'between',
 'boolean_values',
 'boxplot',
 'capitalize',
 'cast',
 'ceil',
 'clip',
 'concat',
 'contains',
 'copy',
 'correlation',
 'cos',
 'cosh',
 'count',
 'count_array',
 'count_between',
 'count_boolean',
 'count_containing',
 'count_credit_card_number',
 'count_data_type',
 'count_datetime',
 'count_duplicated',
 'count_email',
 'count_empty',
 'count_ending_with',
 'count_equal',
 'count_expression',
 'count_float',
 'count_gender',
 'count_greater_than',
 'count_greater_than_equal',
 'count_http_code',
 'count_int',
 'count_ip',
 'count_less_than',
 'count_less_than_equal',
 'count_match',
 'count_match_pattern',
 'count_mismatch',
 'count_missings',
 'count_nan',
 'count_none',
 'count_not_equal',
 'count_nulls',
 'count_numeric',
 'count_object',
 'count_phone_number',
 'count_regex',
 'count_social_security_number',
 'count_starting_with',
 'count_str',
 'count_uniques',
 'count_url',
 'count_values_in',
 'count_zeros',
 'count_zip_code',
 'credit_card_number_values',
 'cross_tab',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'cut',
 'data_type',
 'date_format',
 'date_formats',
 'datetime_values',
 'day',
 'days_between',
 'div',
 'domain',
 'double_metaphone',
 'drop',
 'duplicate',
 'duplicated',
 'email_domain',
 'email_username',
 'email_values',
 'empty',
 'ends_with',
 'equal',
 'exec_agg',
 'exp',
 'expand_contracted_words',
 'expression',
 'extract',
 'fill_na',
 'fingerprint',
 'float_values',
 'floor',
 'format_agg',
 'format_date',
 'frequency',
 'gender_values',
 'get',
 'greater_than',
 'greater_than_equal',
 'groupby',
 'heatmap',
 'hist',
 'host',
 'hour',
 'hours_between',
 'http_code_values',
 'impute',
 'index_to_string',
 'infer_data_types',
 'infer_date_formats',
 'infer_type',
 'inferred_data_type',
 'int_values',
 'ip_values',
 'iqr',
 'item',
 'join',
 'keep',
 'kurtosis',
 'left',
 'lemmatize_verbs',
 'len',
 'less_than',
 'less_than_equal',
 'levenshtein',
 'ln',
 'log',
 'lower',
 'mad',
 'match',
 'match_data_type',
 'match_pattern',
 'match_rating_codex',
 'match_regex',
 'max',
 'max_abs_scaler',
 'mean',
 'median',
 'metaphone',
 'mid',
 'min',
 'min_max_scaler',
 'minute',
 'minutes_between',
 'mismatch',
 'missing',
 'mod',
 'mode',
 'modified_z_score',
 'month',
 'months_between',
 'move',
 'mul',
 'names',
 'nan',
 'nest',
 'ngram_fingerprint',
 'ngrams',
 'none',
 'normalize_chars',
 'normalize_spaces',
 'not_equal',
 'null',
 'num_to_words',
 'numeric_values',
 'nysiis',
 'object_values',
 'one_hot_encode',
 'pad',
 'parse_inferred_types',
 'pattern',
 'pattern_counts',
 'percentile',
 'phone_number_values',
 'port',
 'pos',
 'pow',
 'prod',
 'profile',
 'qcut',
 'quality',
 'range',
 'rdiv',
 'reciprocal',
 'remove',
 'remove_numbers',
 'remove_special_chars',
 'remove_stopwords',
 'remove_urls',
 'remove_white_spaces',
 'rename',
 'replace',
 'replace_regex',
 'reverse',
 'right',
 'round',
 'schema_data_type',
 'second',
 'seconds_between',
 'select',
 'set',
 'set_data_type',
 'set_date_format',
 'sin',
 'sinh',
 'skew',
 'slice',
 'social_security_number_values',
 'sort',
 'soundex',
 'sqrt',
 'standard_scaler',
 'starts_with',
 'std',
 'stem_verbs',
 'str_values',
 'string_to_index',
 'strip',
 'strip_html',
 'sub',
 'sub_domain',
 'substring',
 'sum',
 'tan',
 'tanh',
 'tf_idf',
 'time_between',
 'title',
 'to_boolean',
 'to_datetime',
 'to_float',
 'to_integer',
 'to_list',
 'to_numeric',
 'to_string',
 'to_timestamp',
 'top_domain',
 'trim',
 'unique',
 'unique_values',
 'unnest',
 'unset_data_type',
 'unset_date_format',
 'upper',
 'url_file',
 'url_fragment',
 'url_path',
 'url_query',
 'url_scheme',
 'url_values',
 'value_in',
 'var',
 'weekday',
 'word_count',
 'word_tokenize',
 'year',
 'years_between',
 'z_score',
 'zip_code_values']